In [1]:
import pandas as pd
import sys
sys.path.insert(0,"..\seir\scrap") 
sys.path.append("..") 
from seir.scrap import df

In [25]:
def diff(x):
    t= list(x.sort_values(by="Date Announced",ascending=True)["Patient Number"].diff())[-1]
    return t
x= df.groupby(["States","Latitude","Longitude","Date Announced"],as_index=False)["Patient Number"].count()
x.groupby(["States","Latitude","Longitude"],as_index=False).apply(diff)

States                       Latitude   Longitude
Andaman and Nicobar Islands  11.667026  92.735983    -4.0
Andhra Pradesh               14.750429  78.570026    -1.0
Arunachal Pradesh            27.100399  93.616601     NaN
Assam                        26.749981  94.216667   -14.0
Bihar                        25.785414  87.479973     1.0
Chandigarh                   30.719997  76.780006    -3.0
Chhattisgarh                 22.090420  82.159987    -1.0
Delhi                        28.669993  77.230004     0.0
Goa                          15.491997  73.818001     1.0
Gujarat                      22.258700  71.192400    -3.0
Haryana                      28.450006  77.019991    13.0
Himachal Pradesh             31.100026  77.166597     1.0
Jammu and Kashmir            34.299959  74.466658     0.0
Jharkhand                    23.800393  86.419986     0.0
Karnataka                    12.570381  76.919997    -2.0
Kerala                       8.900373   76.569993     0.0
Ladakh                       34.152588  77.577049     1.0
Madhya Pradesh               21.300391  76.130019     2.0
Maharashtra                  19.250232  73.160175    -1.0
Manipur                      24.799971  93.950017     0.0
Mizoram                      23.710399  92.720015     NaN
Odisha                       19.820430  85.900017     0.0
Puducherry                   11.934994  79.830000    -1.0
Punjab                       31.519974  75.980003     0.0
Rajasthan                    26.449999  74.639981     0.0
Tamil Nadu                   12.920386  79.150042     0.0
Telangana                    18.112400  79.019300     0.0
Uttar Pradesh                27.599981  78.050006     6.0
Uttarakhand                  30.320409  78.050006    -1.0
West Bengal                  22.580390  88.329947     0.0
dtype: float64

In [24]:
x[x.States=="Maharashtra"]

          States   Latitude  Longitude Date Announced  Patient Number
208  Maharashtra  19.250232  73.160175     2020-03-09               2
209  Maharashtra  19.250232  73.160175     2020-03-10               3
210  Maharashtra  19.250232  73.160175     2020-03-11               5
211  Maharashtra  19.250232  73.160175     2020-03-12               4
212  Maharashtra  19.250232  73.160175     2020-03-13               3
213  Maharashtra  19.250232  73.160175     2020-03-14              14
214  Maharashtra  19.250232  73.160175     2020-03-15               2
215  Maharashtra  19.250232  73.160175     2020-03-16               6
216  Maharashtra  19.250232  73.160175     2020-03-17               2
217  Maharashtra  19.250232  73.160175     2020-03-18               4
218  Maharashtra  19.250232  73.160175     2020-03-19               4
219  Maharashtra  19.250232  73.160175     2020-03-20               5
220  Maharashtra  19.250232  73.160175     2020-03-21              10
221  Maharashtra  19.250232  73.160175     2020-03-22              10
222  Maharashtra  19.250232  73.160175     2020-03-23              23
223  Maharashtra  19.250232  73.160175     2020-03-24              10
224  Maharashtra  19.250232  73.160175     2020-03-25              15
225  Maharashtra  19.250232  73.160175     2020-03-26               8
226  Maharashtra  19.250232  73.160175     2020-03-27              26
227  Maharashtra  19.250232  73.160175     2020-03-28              30
228  Maharashtra  19.250232  73.160175     2020-03-29              17
229  Maharashtra  19.250232  73.160175     2020-03-30              35
230  Maharashtra  19.250232  73.160175     2020-03-31              64
231  Maharashtra  19.250232  73.160175     2020-04-01              33
232  Maharashtra  19.250232  73.160175     2020-04-02              88
233  Maharashtra  19.250232  73.160175     2020-04-03              64
234  Maharashtra  19.250232  73.160175     2020-04-04             148